### ISSUE TITLE
Exceptions occur every period of time

### ISSUE THREAD

**Issue by soloHeroo** [XDagger/xmrig2xdag#19]
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Remove(...)
        J:/xmrig2xdag/server/proxy/proxy.go:447
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc00028c6d8})
        J:/xmrig2xdag/server/tcp/worker.go:46 +0x386
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 150101 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc0000cc600)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc0000cc600, {0xc0002a8b60, 0xc})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 110921 [chan send]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Remove(...)
        J:/xmrig2xdag/server/proxy/proxy.go:447
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc0004863f0})
        J:/xmrig2xdag/server/tcp/worker.go:46 +0x386
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 137704 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc000326300)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc000326300, {0xc00059a240, 0xd})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 110911 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc00058d080)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc00058d080, {0xc000314e90, 0xd})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 110828 [select, 24 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartWriter(0xc00024bce0)
        J:/xmrig2xdag/server/xdag/connect.go:48 +0x1c6
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:99 +0xe7

goroutine 110827 [chan send, 23 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartReader(0xc00024bce0)
        J:/xmrig2xdag/server/xdag/connect.go:88 +0x19a
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:97 +0xa5

goroutine 110896 [chan send, 41 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartReader(0xc0000c99d0)
        J:/xmrig2xdag/server/xdag/connect.go:88 +0x19a
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:97 +0xa5

goroutine 110897 [select, 42 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartWriter(0xc0000c99d0)
        J:/xmrig2xdag/server/xdag/connect.go:48 +0x1c6
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:99 +0xe7

goroutine 110948 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc00024d380)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc00024d380, {0xc00091f480, 0xa})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 130654 [chan send]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Remove(...)
        J:/xmrig2xdag/server/proxy/proxy.go:447
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc00028c870})
        J:/xmrig2xdag/server/tcp/worker.go:46 +0x386
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 128834 [chan send]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Remove(...)
        J:/xmrig2xdag/server/proxy/proxy.go:447
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc000208e98})
        J:/xmrig2xdag/server/tcp/worker.go:46 +0x386
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 155577 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc000162d80)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc000162d80, {0xc000772ab0, 0xc})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 164826 [select, 9 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartWriter(0xc000298930)
        J:/xmrig2xdag/server/xdag/connect.go:48 +0x1c6
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:99 +0xe7

goroutine 164825 [chan send, 9 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartReader(0xc000298930)
        J:/xmrig2xdag/server/xdag/connect.go:88 +0x19a
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:97 +0xa5

goroutine 134211 [chan send]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Remove(...)
        J:/xmrig2xdag/server/proxy/proxy.go:447
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc000208eb0})
        J:/xmrig2xdag/server/tcp/worker.go:46 +0x386
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 134227 [semacquire]:
sync.runtime_SemacquireMutex(0xc000dd9d08, 0x65, 0xd06f53)
        C:/Program Files/Go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00004e2d0)
        C:/Program Files/Go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        C:/Program Files/Go/src/sync/mutex.go:81
log.(*Logger).Output(0xc00004e2d0, 0x14, {0xc000198e10, 0x15})
        C:/Program Files/Go/src/log/log.go:165 +0x9c
log.(*Logger).Printf(0xc000051560, {0x1047f93, 0xc0009078c0}, {0xc000dd9e78, 0xc000338968, 0xc000dd9e20})
        C:/Program Files/Go/src/log/log.go:191 +0x4c
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc000162780)
        J:/xmrig2xdag/server/proxy/proxy.go:315 +0x7c
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc000162780, {0xc0007f1d20, 0xd})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 134230 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc0000ccd80)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc0000ccd80, {0xc00059a090, 0xc})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 159135 [select, 15 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartWriter(0xc00010df80)
        J:/xmrig2xdag/server/xdag/connect.go:48 +0x1c6
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:99 +0xe7

goroutine 171987 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc0001b3080)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc0001b3080, {0xc000772ab0, 0xa})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 141317 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc00058db00)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc00058db00, {0xc000203880, 0xb})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 141331 [chan send, 14 minutes]:
github.com/swordlet/xmrig2xdag/xdag.(*Connection).StartReader(0xc00010d9d0)
        J:/xmrig2xdag/server/xdag/connect.go:88 +0x19a
created by github.com/swordlet/xmrig2xdag/xdag.(*Connection).Start
        J:/xmrig2xdag/server/xdag/connect.go:97 +0xa5

goroutine 159163 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc000163e00)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc000163e00, {0xc000b818f0, 0xd})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 178867 [runnable]:
sync.runtime_Semrelease(0xc00007a280, 0x0, 0x36)
        C:/Program Files/Go/src/runtime/sema.go:66 +0x19
sync.(*Mutex).unlockSlow(0x10000006232f67d, 0x12808e0)
        C:/Program Files/Go/src/sync/mutex.go:224 +0x65
sync.(*Mutex).Unlock(0x0)
        C:/Program Files/Go/src/sync/mutex.go:190 +0x29
log.(*Logger).Output(0xc00004e2d0, 0x14, {0xc00000f020, 0x15})
        C:/Program Files/Go/src/log/log.go:185 +0x38a
log.(*Logger).Printf(0x11c, {0x1047f93, 0xc00080a660}, {0xc000d65e78, 0xc000510148, 0xc000d65e20})
        C:/Program Files/Go/src/log/log.go:191 +0x4c
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc0001b3800)
        J:/xmrig2xdag/server/proxy/proxy.go:315 +0x7c
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc0001b3800, {0xc000a01090, 0xc})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 187620 [chan send]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Remove(...)
        J:/xmrig2xdag/server/proxy/proxy.go:447
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc0000067d8})
        J:/xmrig2xdag/server/tcp/worker.go:46 +0x386
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 170163 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc000326f00)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc000326f00, {0xc000a00740, 0xb})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 178854 [IO wait]:
internal/poll.runtime_pollWait(0x280f90e8, 0x72)
        C:/Program Files/Go/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0x18, 0xc0002083d8, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc000570c98, 0x10608d0)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc000570c80, {0xc00032ac01, 0x5ff, 0x5ff})
        C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc000570c80, {0xc00032ac01, 0xd, 0x0})
        C:/Program Files/Go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000007db0, {0xc00032ac01, 0x101000000cee93c, 0xab2db8})
        C:/Program Files/Go/src/net/net.go:183 +0x45
encoding/json.(*Decoder).refill(0xc000915cc0)
        C:/Program Files/Go/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc000915cc0)
        C:/Program Files/Go/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc000915cc0, {0xffab20, 0xc000989848})
        C:/Program Files/Go/src/encoding/json/stream.go:63 +0x78
github.com/swordlet/xmrig2xdag/stratum.(*DefaultServerCodec).ReadRequestHeader(0xc0000a2940, 0xc0000a2960)
        J:/xmrig2xdag/server/stratum/codec.go:61 +0x77
net/rpc.(*Server).readRequestHeader(0xc000913590, {0x10bcc98, 0xc0000a2940})
        C:/Program Files/Go/src/net/rpc/server.go:583 +0x66
net/rpc.(*Server).readRequest(0xc0001b3800, {0x10bcc98, 0xc0000a2940})
        C:/Program Files/Go/src/net/rpc/server.go:543 +0x3b
net/rpc.(*Server).ServeCodec(0xc000913590, {0x10bcc98, 0xc0000a2940})
        C:/Program Files/Go/src/net/rpc/server.go:458 +0x87
github.com/swordlet/xmrig2xdag/stratum.(*Server).ServeCodec(...)
        J:/xmrig2xdag/server/stratum/server.go:105
github.com/swordlet/xmrig2xdag/tcp.SpawnWorker({0x10c18f8, 0xc000007db0})
        J:/xmrig2xdag/server/tcp/worker.go:44 +0x349
created by github.com/swordlet/xmrig2xdag/tcp.StartServer
        J:/xmrig2xdag/server/tcp/server.go:43 +0x527

goroutine 187610 [chan receive]:
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc0001b2a80)
        J:/xmrig2xdag/server/proxy/proxy.go:325 +0xc6
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc0001b2a80, {0xc000194ee0, 0xc})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

goroutine 194662 [semacquire]:
sync.runtime_SemacquireMutex(0xc000e5fd08, 0x65, 0xd06f53)
        C:/Program Files/Go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00004e2d0)
        C:/Program Files/Go/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        C:/Program Files/Go/src/sync/mutex.go:81
log.(*Logger).Output(0xc00004e2d0, 0x14, {0xc0002b5008, 0x15})
        C:/Program Files/Go/src/log/log.go:165 +0x9c
log.(*Logger).Printf(0x11f, {0x1047f93, 0xc0008ca0c0}, {0xc000e5fe78, 0xc000707e88, 0xc000e5fe20})
        C:/Program Files/Go/src/log/log.go:191 +0x4c
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).shutdown(0xc000162c00)
        J:/xmrig2xdag/server/proxy/proxy.go:315 +0x7c
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run.func1()
        J:/xmrig2xdag/server/proxy/proxy.go:146 +0x1d
github.com/swordlet/xmrig2xdag/proxy.(*Proxy).Run(0xc000162c00, {0xc00059b990, 0xc})
        J:/xmrig2xdag/server/proxy/proxy.go:164 +0x3f0
created by github.com/swordlet/xmrig2xdag/proxy.(*Mining).Login
        J:/xmrig2xdag/server/proxy/mining.go:83 +0x2c5

E:\xdag_win64_proxy+rig_v1.0.4>

**Comment by FSOL06** [comment]
@swordlet @Sofarlemineur Should be close now.
